### ISSUE TITLE
Missing 20B_tokenizer.json

### ISSUE THREAD

**Issue by akshish1** [MarisaJH/CounterSpeechGenerator#4]
Hey Marisa,
During the training of GPT3, I am missing a tokenizer_file which is called "20B_tokenizer.json". I tried to search in hugging face tokenizer library but I can't find a perfect matching. Could you please give me a clue or copy of such json? 
Thanks!

**Comment by MarisaJH** [comment]
hey, why don't you try this one: https://the-eye.eu/public/AI/models/GPT-NeoX-20B/slim_weights/20B_tokenizer.json

I don't remember exactly what I used but see if this works
